### ISSUE TITLE
maven ?

### ISSUE THREAD

**Issue by Dominilk01** [Matt-MX/DisplayNameTags#21]
In your README it seam that its also ment for devs, but i can't find any maven link for dependencies by looking you seam publish to "https://maven.pvphub.me/#/releases/com/mattmx" but can't any trace of it. (mavenCentral also don't have)

Do its meant to be directly put on the src of my plugin folder ?

**Comment by Matt-MX** [comment]
Currently haven't added to my maven but you can use a local dependency through your own libs directory and depending on the jar itself.
