### ISSUE TITLE
Placeholders for TAB not working.

### ISSUE THREAD

**Issue by NathanTBeene** [Matt-MX/DisplayNameTags#31]
I'm not sure if I am just not understanding, but I cannot get the nametags to properly update with the %player_name% placeholder. I've also tried %player% as that's what is being used inside TAB. 

It's just not updating at all.

**Comment by Matt-MX** [comment]
Make sure you have the `Players` expansion downloaded, placeholder api no longer downloads it automatically so you must yourself with `/papi ecloud download Players` and `/papi reload`.

**Comment by Matt-MX** [comment]
You can also check if you have it installed by running `/papi parse me %player_name%`

**Comment by NathanTBeene** [comment]
Alright the player name is now working, however I would like to hook it up with the TAB conditional placeholder. When doing the `/tab parse` I know it's working, however there is no `/papi parse` for it even after including the TAB addon for placeholder.

Is there something I am missing trying to use conditionals? Or have those not been implemented yet?

**Comment by NathanTBeene** [comment]
Alright, for anyone wondering I figured it out.

When using TAB through palceholderAPI you need to do `%tab_placeholder_<placeholder>%`

**Comment by NathanTBeene** [comment]
Alright, for anyone wondering I figured it out.

When using TAB through palceholderAPI you need to do %tab_placeholder_<placeholder>%
