### ISSUE TITLE
[Question] How to make an animated nametag?

### ISSUE THREAD

**Issue by PhoenixFireTea** [Matt-MX/DisplayNameTags#36]
I was just wondering how would I make an animated nametag like what is seen in the gif in the README? I've made animated text in TAB, but I'm not sure how to do it in displaynametags.

![nametags](https://github.com/user-attachments/assets/fe7aa2f5-ecb4-4467-80f5-16ad5ee3e4c1)

**Comment by Matt-MX** [comment]
Take a look at https://github.com/NEZNAMY/TAB/wiki/Placeholders#placeholderapi

**Comment by PhoenixFireTea** [comment]
Thank you! For anyone who finds this and is also wondering, just make an animation in TAB, then set your displaynametags text to be `%tab_placeholder_animation:(animationname)%`.
