### ISSUE TITLE
Scale property not working

### ISSUE THREAD

**Issue by bumpyJake** [Matt-MX/DisplayNameTags#37]
Setting "scale" in the config for either default or groups does not change the size of the displays

**Comment by Matt-MX** [comment]
@bumpyJake please show the config, scale is supported

**Comment by bumpyJake** [comment]
Ahh I wasn't aware you had to specify x y z, thank you!

Also question, would it ever be possible to have different scale properties for different lines?

**Comment by bumpyJake** [comment]
Fair enough! Is there any API documentation that exists/is planned to? Or no

**Comment by Matt-MX** [comment]
> Fair enough! Is there any API documentation that exists/is planned to? Or no

I need to write some i only just make the wiki page but havent added anything to it
