### ISSUE TITLE
[suggestion] per group text display customization

### ISSUE THREAD

**Issue by Ranksu10** [Matt-MX/DisplayNameTags#41]
Ability to customize the display text per group and not just the background.
![image](https://github.com/user-attachments/assets/0a247aab-292e-4078-b11e-6141fb918fc9)

**Comment by Matt-MX** [comment]
This should be working. Is it not?

**Comment by Matt-MX** [comment]
#42

**Comment by Ranksu10** [comment]
> This should be working. Is it not?

Well I just tested by creating an "admin" group and it keeps displaying the default text display.

**Comment by Matt-MX** [comment]
Ah its been a bit weird recently do you mind sending your config please :)

**Comment by Ranksu10** [comment]
Hey, sorry for the delay. I just tested and it works. I did something wrong apparently.

**Comment by Matt-MX** [comment]
No problem mate
